language: php

php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true

# faster builds on new travis setup not using sudo
sudo: false


install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction || tree -L2 vendor
  - tree -L2 vendor 

script:
  - ./vendor/bin/phpunit
